language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t milkplease/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true milkplease/docker-react npm run test